version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    
  kafka:
    image: kafka:latest
    restart: always
    links:
      - zookeeper:zookeeper
    entrypoint: /opt/bin/start.sh

  cassandra:
    image: cassandra:latest
    restart: always

  influxdb:
    image: smack/influxdb:1.2.4
    restart: always
    ports:
      - 8083:8083
      - 8086:8086

  flink:
    image: smack/flink:1.0
    restart: always
    links:
      - cassandra:cassandra
      - influxdb:influxdb
      - kafka:kafka
    entrypoint: /opt/bin/start.sh

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000

  spark_master:
    image: smack/spark_master:2.7.3_2.10_2
    restart: always
    links:
      - cassandra:cassandra
    entrypoint: /opt/bin/start.sh

  spark_slave:
    image: smack/spark_slave:2.7.3_2.10_2
    restart: always
    links:
      - cassandra:cassandra
      - spark_master:spark_master
    entrypoint: /opt/bin/start.sh

  spark_app:
    image: smack/spark_app:1.0
    restart: always
    links:
      - cassandra:cassandra
      - spark_master:spark_master
    entrypoint: /opt/bin/start.sh
    
  akka-instream:
    image: smack/akka:1.0
    restart: always
    ports:
      - 9090:9090
    links:
      - kafka:kafka
      - spark_app:rpc
    entrypoint: /opt/bin/start.sh instream
    
  akka-outstream:
    image: smack/akka:1.0
    restart: always
    ports:
      - 9091:9091
    links:
      - cassandra:cassandra
      - spark_app:rpc
    entrypoint: /opt/bin/start.sh outstream